#!/usr/bin/env node
/**
 * create_universal_user.js
 *
 * Small helper to generate a bcrypt-hashed password and print an SQL INSERT
 * statement you can run in pgAdmin / psql to create a temporary "universal"
 * user account. Run locally, copy the SQL to your DB admin, or paste into pgAdmin.
 *
 * Usage:
 * node create_universal_user.js --username universal_temp --password "My$ecret123" \
 *   --employee_id temp001 --name "Temporary User" --role User --plant "MainPlant"
 *
 * Notes:
 * - This does NOT modify your database automatically; it only prints SQL.
 * - Use a strong temporary password, and remove or rotate the account after use.
 */
const bcrypt = require('bcryptjs');
// Minimal argv parsing (no external deps)
const argv = {};
for (let i = 2; i < process.argv.length; i++) {
    const arg = process.argv[i];
    if (arg.startsWith('--')) {
        const key = arg.slice(2);
        const val = process.argv[i + 1] && !process.argv[i + 1].startsWith('--') ? process.argv[i + 1] : true;
        argv[key] = val;
        if (val !== true)
            i++;
    }
}
const required = ['username', 'password', 'employee_id', 'name', 'role', 'plant'];
for (const r of required) {
    if (!argv[r]) {
        console.error(`Missing required argument --${r}`);
        console.error('Usage: node create_universal_user.js --username <username> --password <password> --employee_id <id> --name "Full Name" --role User --plant "PlantName"');
        process.exit(1);
    }
}
const username = argv.username;
const password = argv.password;
const employee_id = argv.employee_id;
const name = argv.name;
const role = argv.role;
const plant = argv.plant;
async function make() {
    try {
        const saltRounds = 10;
        const hashed = await bcrypt.hash(password, saltRounds);
        // Escape single quotes for SQL
        const esc = s => s.replace(/'/g, "''");
        const sql = `-- Generated by backend/scripts/create_universal_user.js\nINSERT INTO users (employee_id, username, password, name, role, plant, created_at) VALUES ('${esc(employee_id)}', '${esc(username)}', '${esc(hashed)}', '${esc(name)}', '${esc(role)}', '${esc(plant)}', NOW());`;
        console.log('\n===== COPY/PASTE THIS SQL INTO YOUR DATABASE (pgAdmin / psql) =====\n');
        console.log(sql);
        console.log('\n===== NOTES =====');
        console.log('- After testing, remove the user with:');
        console.log(`  DELETE FROM users WHERE username = '${esc(username)}';`);
        console.log('- Or change password to a random value and/or set a disabled flag if you have one.');
        console.log('- Ensure the account has minimal role/permissions (use role=User if possible).');
        console.log('\n');
    }
    catch (err) {
        console.error('Error generating hash:', err);
        process.exit(1);
    }
}
make();
